### ISSUE TITLE
Set union and intersection

### ISSUE THREAD

**Issue by MatthewGotham** [rawlins/lambda-notebook#12]
I really appreciate this resource. A request: given that you have set types and membership as a term constructor, could you add set intersection and union as term constructors too? I have no idea how hard that would be, but ideally you'd also have reductions so that e.g. {x, y} U {z} would reduce to {x, y, z}.

**Comment by rawlins** [comment]
Thanks for the note. Adding the notation would be very easy indeed, so I can look into this soon. Adding reductions (in a really general way) is a bit trickier because it requires robust equality checking (/unification). But, it is not different than other reduction stuff I want to improve, so I'll definitely put it on the list, and the case you mention would be easy to get with only syntactic equality.
